export const alumniData = [
  {
    id: 1,
    name: "Aditya Raj Singh Ranawat",
    college: "Poornima College of Engineering",
    join_year: 2024,
    passing_year: 2028,
    company: "Google",
    location: "Gurgaon",
    skills: ["Web Development", "AI", "Next.js"],
    role: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/aditya-raj-singh-ranawat/",
    photo: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: 2,
    name: "Ravi Sharma",
    college: "Poornima College of Engineering",
    join_year: 2024,
    passing_year: 2028,
    company: "Amazon",
    location: "Bangalore",
    skills: ["React", "Node.js", "MongoDB"],
    role: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/ravi-sharma/",
    photo: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 3,
    name: "Priya Mehta",
    college: "IIT Delhi",
    join_year: 2024,
    passing_year: 2028,
    company: "Microsoft",
    location: "Hyderabad",
    skills: ["Python", "Data Science"],
    role: "Data Scientist",
    linkedin: "https://www.linkedin.com/in/priya-mehta/",
    photo: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: 4,
    name: "Karan Verma",
    college: "Jaipur Engineering College",
    join_year: 2023,
    passing_year: 2027,
    company: "Meta",
    location: "Mumbai",
    skills: ["UI/UX", "Figma", "Frontend"],
    role: "UI/UX Designer",
    linkedin: "https://www.linkedin.com/in/karan-verma/",
    photo: "https://randomuser.me/api/portraits/men/85.jpg",
  },
  {
    id: 5,
    name: "Ananya Gupta",
    college: "Poornima College of Engineering",
    join_year: 2022,
    passing_year: 2026,
    company: "Netflix",
    location: "Delhi",
    skills: ["Machine Learning", "Cloud", "Python"],
    role: "ML Engineer",
    linkedin: "https://www.linkedin.com/in/ananya-gupta/",
    photo: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    id: 6,
    name: "Vikash Kumar",
    college: "Manipal Institute of Technology",
    join_year: 2023,
    passing_year: 2027,
    company: "Tesla",
    location: "Pune",
    skills: ["Embedded Systems", "C++", "IoT"],
    role: "Embedded Software Engineer",
    linkedin: "https://www.linkedin.com/in/vikash-kumar/",
    photo: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 7,
    name: "Sneha Patel",
    college: "IIT Bombay",
    join_year: 2021,
    passing_year: 2025,
    company: "Adobe",
    location: "Noida",
    skills: ["Creative Design", "Photoshop", "Illustrator"],
    role: "Creative Director",
    linkedin: "https://www.linkedin.com/in/sneha-patel/",
    photo: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    id: 8,
    name: "Rohit Agarwal",
    college: "Rajasthan Technical University",
    join_year: 2022,
    passing_year: 2026,
    company: "Spotify",
    location: "Chennai",
    skills: ["Mobile Development", "Swift", "Kotlin"],
    role: "Mobile App Developer",
    linkedin: "https://www.linkedin.com/in/rohit-agarwal/",
    photo: "https://randomuser.me/api/portraits/men/67.jpg",
  },
  {
    id: 9,
    name: "Kavya Reddy",
    college: "Poornima College of Engineering",
    join_year: 2023,
    passing_year: 2027,
    company: "Uber",
    location: "Bangalore",
    skills: ["Product Management", "Analytics", "Strategy"],
    role: "Product Manager",
    linkedin: "https://www.linkedin.com/in/kavya-reddy/",
    photo: "https://randomuser.me/api/portraits/women/73.jpg",
  },
  {
    id: 10,
    name: "Arjun Singh",
    college: "Jaipur National University",
    join_year: 2024,
    passing_year: 2028,
    company: "Salesforce",
    location: "Gurgaon",
    skills: ["Salesforce CRM", "Apex", "Lightning"],
    role: "Salesforce Developer",
    linkedin: "https://www.linkedin.com/in/arjun-singh/",
    photo: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    id: 11,
    name: "Nisha Jain",
    college: "NIT Jaipur",
    join_year: 2022,
    passing_year: 2026,
    company: "Oracle",
    location: "Pune",
    skills: ["Database Management", "SQL", "Oracle DB"],
    role: "Database Administrator",
    linkedin: "https://www.linkedin.com/in/nisha-jain/",
    photo: "https://randomuser.me/api/portraits/women/42.jpg",
  },
  {
    id: 12,
    name: "Akash Malhotra",
    college: "IIT Roorkee",
    join_year: 2021,
    passing_year: 2025,
    company: "LinkedIn",
    location: "Mumbai",
    skills: ["DevOps", "AWS", "Docker"],
    role: "DevOps Engineer",
    linkedin: "https://www.linkedin.com/in/akash-malhotra/",
    photo: "https://randomuser.me/api/portraits/men/58.jpg",
  },
  {
    id: 13,
    name: "Deepika Rao",
    college: "Arya College of Engineering",
    join_year: 2023,
    passing_year: 2027,
    company: "Airbnb",
    location: "Hyderabad",
    skills: ["Full Stack", "Vue.js", "PostgreSQL"],
    role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/deepika-rao/",
    photo: "https://randomuser.me/api/portraits/women/37.jpg",
  },
  {
    id: 14,
    name: "Siddharth Bansal",
    college: "Poornima College of Engineering",
    join_year: 2022,
    passing_year: 2026,
    company: "Paytm",
    location: "Noida",
    skills: ["Cybersecurity", "Ethical Hacking", "Network Security"],
    role: "Security Analyst",
    linkedin: "https://www.linkedin.com/in/siddharth-bansal/",
    photo: "https://randomuser.me/api/portraits/men/23.jpg",
  },
  {
    id: 15,
    name: "Tanya Khanna",
    college: "Jaipur Engineering College",
    join_year: 2024,
    passing_year: 2028,
    company: "PayPal",
    location: "Chennai",
    skills: ["Blockchain", "Solidity", "Web3"],
    role: "Blockchain Developer",
    linkedin: "https://www.linkedin.com/in/tanya-khanna/",
    photo: "https://randomuser.me/api/portraits/women/81.jpg",
  },
  {
    id: 16,
    name: "Mayank Goyal",
    college: "IIT Kanpur",
    join_year: 2021,
    passing_year: 2025,
    company: "Zoom",
    location: "Bangalore",
    skills: ["Video Streaming", "WebRTC", "Multimedia"],
    role: "Video Technology Engineer",
    linkedin: "https://www.linkedin.com/in/mayank-goyal/",
    photo: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: 17,
    name: "Ishita Agrawal",
    college: "BITS Pilani",
    join_year: 2023,
    passing_year: 2027,
    company: "Shopify",
    location: "Delhi",
    skills: ["E-commerce", "Ruby on Rails", "GraphQL"],
    role: "E-commerce Developer",
    linkedin: "https://www.linkedin.com/in/ishita-agrawal/",
    photo: "https://randomuser.me/api/portraits/women/56.jpg",
  },
  {
    id: 18,
    name: "Harsh Mittal",
    college: "Malviya National Institute of Technology",
    join_year: 2022,
    passing_year: 2026,
    company: "Nvidia",
    location: "Pune",
    skills: ["GPU Programming", "CUDA", "Computer Graphics"],
    role: "Graphics Software Engineer",
    linkedin: "https://www.linkedin.com/in/harsh-mittal/",
    photo: "https://randomuser.me/api/portraits/men/39.jpg",
  },
  {
    id: 19,
    name: "Ritika Desai",
    college: "Poornima College of Engineering",
    join_year: 2024,
    passing_year: 2028,
    company: "Dropbox",
    location: "Mumbai",
    skills: ["Cloud Storage", "Distributed Systems", "Go"],
    role: "Cloud Engineer",
    linkedin: "https://www.linkedin.com/in/ritika-desai/",
    photo: "https://randomuser.me/api/portraits/women/92.jpg",
  },
  {
    id: 20,
    name: "Abhinav Tiwari",
    college: "Jaipur National University",
    join_year: 2023,
    passing_year: 2027,
    company: "Intel",
    location: "Bangalore",
    skills: ["Hardware Design", "Verilog", "FPGA"],
    role: "Hardware Engineer",
    linkedin: "https://www.linkedin.com/in/abhinav-tiwari/",
    photo: "https://randomuser.me/api/portraits/men/77.jpg",
  },
  {
    id: 21,
    name: "Pooja Kashyap",
    college: "IIT Madras",
    join_year: 2021,
    passing_year: 2025,
    company: "ByteDance",
    location: "Gurgaon",
    skills: ["Content Algorithms", "Recommendation Systems", "Scala"],
    role: "Algorithm Engineer",
    linkedin: "https://www.linkedin.com/in/pooja-kashyap/",
    photo: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 22,
    name: "Yash Chandra",
    college: "Rajasthan Technical University",
    join_year: 2022,
    passing_year: 2026,
    company: "Razorpay",
    location: "Bangalore",
    skills: ["Payment Systems", "FinTech", "Microservices"],
    role: "Payment Engineer",
    linkedin: "https://www.linkedin.com/in/yash-chandra/",
    photo: "https://randomuser.me/api/portraits/men/63.jpg",
  },
  {
    id: 23,
    name: "Shreya Kapoor",
    college: "Arya College of Engineering",
    join_year: 2024,
    passing_year: 2028,
    company: "Snapchat",
    location: "Mumbai",
    skills: ["AR/VR", "Computer Vision", "Unity"],
    role: "AR Engineer",
    linkedin: "https://www.linkedin.com/in/shreya-kapoor/",
    photo: "https://randomuser.me/api/portraits/women/34.jpg",
  },
  {
    id: 24,
    name: "Nikhil Saxena",
    college: "Poornima College of Engineering",
    join_year: 2021,
    passing_year: 2025,
    company: "Hotstar",
    location: "Chennai",
    skills: ["Live Streaming", "CDN", "Real-time Systems"],
    role: "Streaming Engineer",
    linkedin: "https://www.linkedin.com/in/nikhil-saxena/",
    photo: "https://randomuser.me/api/portraits/men/48.jpg",
  },
  {
    id: 25,
    name: "Aditi Bhardwaj",
    college: "Jaipur Engineering College",
    join_year: 2023,
    passing_year: 2027,
    company: "GitHub",
    location: "Hyderabad",
    skills: ["Git", "CI/CD", "Developer Tools"],
    role: "Developer Experience Engineer",
    linkedin: "https://www.linkedin.com/in/aditi-bhardwaj/",
    photo: "https://randomuser.me/api/portraits/women/71.jpg",
  },
  {
    id: 26,
    name: "Rahul Nanda",
    college: "IIT Kharagpur",
    join_year: 2022,
    passing_year: 2026,
    company: "Discord",
    location: "Noida",
    skills: ["Real-time Communication", "WebSocket", "Elixir"],
    role: "Backend Engineer",
    linkedin: "https://www.linkedin.com/in/rahul-nanda/",
    photo: "https://randomuser.me/api/portraits/men/89.jpg",
  },
  {
    id: 27,
    name: "Swati Ghosh",
    college: "NIT Jaipur",
    join_year: 2024,
    passing_year: 2028,
    company: "Figma",
    location: "Pune",
    skills: ["Design Systems", "Prototyping", "JavaScript"],
    role: "Design Engineer",
    linkedin: "https://www.linkedin.com/in/swati-ghosh/",
    photo: "https://randomuser.me/api/portraits/women/46.jpg",
  },
  {
    id: 28,
    name: "Kartik Pandey",
    college: "JECRC University",
    join_year: 2021,
    passing_year: 2025,
    company: "Atlassian",
    location: "Bangalore",
    skills: ["Agile Tools", "Project Management", "Confluence"],
    role: "Product Engineer",
    linkedin: "https://www.linkedin.com/in/kartik-pandey/",
    photo: "https://randomuser.me/api/portraits/men/26.jpg",
  },
  {
    id: 29,
    name: "Neha Thakur",
    college: "Poornima College of Engineering",
    join_year: 2023,
    passing_year: 2027,
    company: "Canva",
    location: "Delhi",
    skills: ["Design Automation", "Image Processing", "TypeScript"],
    role: "Frontend Engineer",
    linkedin: "https://www.linkedin.com/in/neha-thakur/",
    photo: "https://randomuser.me/api/portraits/women/83.jpg",
  },
  {
    id: 30,
    name: "Varun Malhotra",
    college: "Jaipur National University",
    join_year: 2022,
    passing_year: 2026,
    company: "Slack",
    location: "Mumbai",
    skills: ["Team Collaboration", "Chat Systems", "Real-time Data"],
    role: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/varun-malhotra/",
    photo: "https://randomuser.me/api/portraits/men/54.jpg",
  },
  {
    id: 31,
    name: "Anjali Vyas",
    college: "Amity University Rajasthan",
    join_year: 2024,
    passing_year: 2028,
    company: "Coinbase",
    location: "Gurgaon",
    skills: ["Cryptocurrency", "Trading Systems", "Risk Management"],
    role: "Crypto Engineer",
    linkedin: "https://www.linkedin.com/in/anjali-vyas/",
    photo: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: 32,
    name: "Gaurav Singhal",
    college: "IIT Guwahati",
    join_year: 2021,
    passing_year: 2025,
    company: "PhonePe",
    location: "Bangalore",
    skills: ["Recommendation Algorithms", "Big Data", "Spark"],
    role: "Data Engineer",
    linkedin: "https://www.linkedin.com/in/gaurav-singhal/",
    photo: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    id: 33,
    name: "Preeti Joshi",
    college: "Arya College of Engineering",
    join_year: 2023,
    passing_year: 2027,
    company: "Ubisoft",
    location: "Pune",
    skills: ["Game Development", "Unreal Engine", "Graphics Programming"],
    role: "Game Developer",
    linkedin: "https://www.linkedin.com/in/preeti-joshi/",
    photo: "https://randomuser.me/api/portraits/women/57.jpg",
  },
  {
    id: 34,
    name: "Sumit Chaudhary",
    college: "Poornima College of Engineering",
    join_year: 2022,
    passing_year: 2026,
    company: "ISRO",
    location: "Bangalore",
    skills: ["Aerospace Engineering", "Simulation", "MATLAB"],
    role: "Flight Software Engineer",
    linkedin: "https://www.linkedin.com/in/sumit-chaudhary/",
    photo: "https://randomuser.me/api/portraits/men/82.jpg",
  },
  {
    id: 35,
    name: "Divya Khurana",
    college: "Jaipur Engineering College",
    join_year: 2024,
    passing_year: 2028,
    company: "Palantir",
    location: "Hyderabad",
    skills: ["Data Analytics", "Government Tech", "Java"],
    role: "Forward Deployed Engineer",
    linkedin: "https://www.linkedin.com/in/divya-khurana/",
    photo: "https://randomuser.me/api/portraits/women/95.jpg",
  },
  {
    id: 36,
    name: "Arun Bhat",
    college: "Manipal Institute of Technology",
    join_year: 2021,
    passing_year: 2025,
    company: "Jio",
    location: "Mumbai",
    skills: ["Streaming Media", "Smart TV", "Embedded Systems"],
    role: "Media Software Engineer",
    linkedin: "https://www.linkedin.com/in/arun-bhat/",
    photo: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    id: 37,
    name: "Meera Ahluwalia",
    college: "IIT Delhi",
    join_year: 2023,
    passing_year: 2027,
    company: "Swiggy",
    location: "Bangalore",
    skills: ["Logistics", "Route Optimization", "Algorithms"],
    role: "Logistics Engineer",
    linkedin: "https://www.linkedin.com/in/meera-ahluwalia/",
    photo: "https://randomuser.me/api/portraits/women/24.jpg",
  },
  {
    id: 38,
    name: "Pranav Kulkarni",
    college: "Rajasthan Technical University",
    join_year: 2022,
    passing_year: 2026,
    company: "BigBasket",
    location: "Bangalore",
    skills: ["E-commerce", "Inventory Management", "Machine Learning"],
    role: "ML Engineer",
    linkedin: "https://www.linkedin.com/in/pranav-kulkarni/",
    photo: "https://randomuser.me/api/portraits/men/59.jpg",
  },
  {
    id: 39,
    name: "Sakshi Arora",
    college: "Poornima College of Engineering",
    join_year: 2024,
    passing_year: 2028,
    company: "CRED",
    location: "Bangalore",
    skills: ["Financial Software", "Trading Platforms", "React Native"],
    role: "Mobile Engineer",
    linkedin: "https://www.linkedin.com/in/sakshi-arora/",
    photo: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    id: 40,
    name: "Tarun Mehta",
    college: "NIT Jaipur",
    join_year: 2021,
    passing_year: 2025,
    company: "Zendesk",
    location: "Chennai",
    skills: ["Customer Support", "CRM", "API Development"],
    role: "API Engineer",
    linkedin: "https://www.linkedin.com/in/tarun-mehta/",
    photo: "https://randomuser.me/api/portraits/men/93.jpg",
  },
  {
    id: 41,
    name: "Priyanka Modi",
    college: "Jaipur National University",
    join_year: 2023,
    passing_year: 2027,
    company: "BYJU'S",
    location: "Bangalore",
    skills: ["EdTech", "Learning Analytics", "Content Management"],
    role: "Education Technology Engineer",
    linkedin: "https://www.linkedin.com/in/priyanka-modi/",
    photo: "https://randomuser.me/api/portraits/women/31.jpg",
  },
  {
    id: 42,
    name: "Rajesh Kumar",
    college: "JECRC University",
    join_year: 2022,
    passing_year: 2026,
    company: "MakeMyTrip",
    location: "Gurgaon",
    skills: ["Travel Tech", "Booking Systems", "Microservices"],
    role: "Backend Engineer",
    linkedin: "https://www.linkedin.com/in/rajesh-kumar/",
    photo: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 43,
    name: "Shivani Gupta",
    college: "Arya College of Engineering",
    join_year: 2024,
    passing_year: 2028,
    company: "HealthifyMe",
    location: "Bangalore",
    skills: ["Health Tech", "IoT", "Mobile Apps"],
    role: "IoT Engineer",
    linkedin: "https://www.linkedin.com/in/shivani-gupta/",
    photo: "https://randomuser.me/api/portraits/women/76.jpg",
  },
  {
    id: 44,
    name: "Aman Srivastava",
    college: "Poornima College of Engineering",
    join_year: 2021,
    passing_year: 2025,
    company: "Freshworks",
    location: "Chennai",
    skills: ["Communication APIs", "SMS", "Voice Services"],
    role: "Communications Developer",
    linkedin: "https://www.linkedin.com/in/aman-srivastava/",
    photo: "https://randomuser.me/api/portraits/men/44.jpg",
  },
  {
    id: 45,
    name: "Ritu Singh",
    college: "Amity University Rajasthan",
    join_year: 2023,
    passing_year: 2027,
    company: "Notion",
    location: "Delhi",
    skills: ["Project Management", "Team Collaboration", "Task Automation"],
    role: "Product Engineer",
    linkedin: "https://www.linkedin.com/in/ritu-singh/",
    photo: "https://randomuser.me/api/portraits/women/88.jpg",
  }
];